@baseUrl = http://localhost:3000

### Register
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "userC3",
    "password": "password123"
}

### Login
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "userC3",
    "password": "password123"
}

### Profile Route
@token = {{login.response.body.token}}
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}
